config/routes.rb
Quiz::Application.routes.draw do
  get "home/index"
  devise_for :users
  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  get "challenge_maester/index"
  post "challenge_maester/start"
  get "challenge_maester/start"
  get "challenge_maester/question"
  post "challenge_maester/question"
  post "challenge_maester/answer"
  get "challenge_maester/end"

  get "challenge_archmaester/index"
  post "challenge_archmaester/start"
  get "challenge_archmaester/start"
  get "challenge_archmaester/question"
  post "challenge_archmaester/question"
  post "challenge_archmaester/answer"
  get "challenge_archmaester/end"

  post "choices/create"
  post "choices/destroy"
  resources :questions
  root :to => "home#index"
  resources :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all

    @scoreboards_maester = Scoreboard.where("score_type = 'maester'")
    @high_score_sorted_array_of_hashes_maester = @scoreboards_maester.sort_by { |hsh| hsh[:score] }.reverse
    @count_maester = 1 
    @is_first_score_maester = "true" 
    @previous_score_maester = 9999999999

    @scoreboards_archmaester = Scoreboard.where("score_type = 'archmaester'")
    @high_score_sorted_array_of_hashes_archmaester = @scoreboards_archmaester.sort_by { |hsh| hsh[:score] }.reverse
    @count_archmaester = 1
    @is_first_score_archmaester = "true"
    @previous_score_archmaester = 9999999999
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if current_user && current_user.admin? %>
<br /><%= link_to "Add Questions", questions_path %>
<% else %>
<% end %>

<h1>Welcome to the A Song of Ice and Fire Trivia Challenge!!!</h1>
<p>Choose your level of lore mastery:</p>

<p><%= link_to "Alcolyte", quiz_index_path %> (take a short quiz of EASY questions: no sign-in required!)</p>
<p><%= link_to "Maester", challenge_maester_index_path %> (take the challenge of MEDIUM questions: 100 questions: see where you rank against others!)<p/>
<p><%= link_to "Archmaester", challenge_archmaester_index_path %> (take the challenge of HARD questions, only true masters of Westeros history and lore will succeed: 100 questions: see where you rank against others!)</p>
<p></p>
<body>

<!-- Main Table(You can define padding accordingly) -->
<table width="100%" border="1" cellspacing="0" cellpadding="5">
<tr>
<td width="50%">

<!-- Table on left side -->
<table width="100%" border="1" cellspacing="0" cellpadding="1">
<tr>
    <th>Place</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Score</th>
    <th>House</th>
    <th>Profile</th>
</tr>

<h1>Maester's Challenge <br /> High Scores</h1>
<% @high_score_sorted_array_of_hashes_maester.each do |scb| %>
 <tr>
        <% if @is_first_score_maester == "true" %>
                <% @is_first_score_maester = "false" %>
                <% @previous_score_maester = scb.score %>
        <% else %>
                <% if @previous_score_maester == scb.score %>
                <% else %>
                        <% @count_maester = @count_maester + 1 %>
                        <% @previous_score_maester = scb.score %>
                <% end %>
        <% end %>

   <td><%= @count_maester.ordinalize %></td>
   <td><%= scb.user.first_name %></td>
   <td><%= scb.user.last_name %></td>
   <td><%= scb.score %></td>
   <td><%= scb.user.house_allegiance %>
   <td><%= link_to "details", user_path(:id => scb.user_id) %>
  </tr>
<% end %>


</table>
<!-- END -->
</td>
<td width="50%">

<!-- Table on right side -->
<table width="100%" border="1" cellspacing="0" cellpadding="1">
<tr>
    <th>Place</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Score</th>
    <th>House</th>
    <th>Profile</th>
</tr>

<h1>Archmaester's Challenge <br /> High Scores</h1>
<% @high_score_sorted_array_of_hashes_archmaester.each do |scb| %>
 <tr>
        <% if @is_first_score_archmaester == "true" %>
                <% @is_first_score_archmaester = "false" %>
                <% @previous_score_archmaester = scb.score %>
        <% else %>
                <% if @previous_score_archmaester == scb.score %>
                <% else %>
                        <% @count_archmaester = @count_archmaester + 1 %>
                        <% @previous_score_archmaester = scb.score %>
                <% end %>
        <% end %>

   <td><%= @count_archmaester.ordinalize %></td>
   <td><%= scb.user.first_name %></td>
   <td><%= scb.user.last_name %></td>
   <td><%= scb.score %></td>
   <td><%= scb.user.house_allegiance %>
   <td><%= link_to "details", user_path(:id => scb.user_id) %>
  </tr>
<% end %>

</table>
<!-- END -->
</td>
</tr>
</table>

<!-- END OF MAIN TABLE -->
</body>