config/routes.rb
Quiz::Application.routes.draw do
  get "home/index"
  devise_for :users
  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  get "challenge_maester/index"
  post "challenge_maester/start"
  get "challenge_maester/start"
  get "challenge_maester/question"
  post "challenge_maester/question"
  post "challenge_maester/answer"
  get "challenge_maester/end"

  get "challenge_archmaester/index"
  post "challenge_archmaester/start"
  get "challenge_archmaester/start"
  get "challenge_archmaester/question"
  post "challenge_archmaester/question"
  post "challenge_archmaester/answer"
  get "challenge_archmaester/end"

  post "choices/create"
  post "choices/destroy"
  resources :questions
  root :to => "home#index"
  resources :users

end

app/controllers/challenge_archmaester_controller.rb
class ChallengeArchmaesterController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def start
         @user = current_user
         reset_session
         sign_in(@user, :bypass => true)

	 total = 10
         all = Question.where("question_type = 'archmaester'").map {|x| x.id}
	 session[:questions] = all.sort_by{rand}[0..(total-1)]
	 
	 session[:total]   = total
	 session[:current] = 0
	 session[:correct] = 0
	 
	 redirect_to :action => "question"
  end

  def question
 	 @current = session[:current]
	 @total   = session[:total]
	 
	 if @current >= @total
		redirect_to :action => "end"
		return
	 end
	 
	 @question = Question.find(session[:questions][@current])
	 @choices = @question.choices.sort_by{rand}
	 
	 session[:question] = @question
	 session[:choices] = @choices 
  end

  def answer
         @current = session[:current]
	 @total   = session[:total]
	 
	 choiceid = params[:choice]
	 
	 @question = session[:question]
	 @choices  = session[:choices]




         @used_id_with_question_text_array = []
         @questioncounters = QuestionCounter.all
         @questioncounters.each do |qc|
                @used_id_with_question_text_array << (qc.used_session_id+qc.question_text)
         end

   if @used_id_with_question_text_array.include?(request.session_options[:id]+@question.text)
         redirect_to :action => "question"
	 flash[:notice] = "STOP HITTING THE BACK BUTTON IN YOUR BROWSER! YOUR ATTEMPT TO CHEAT HAS BEEN THWARTED!"
         return
   else

         @questioncounter = QuestionCounter.new
         @questioncounter.used_session_id = request.session_options[:id]
         @questioncounter.question_text = @question.text
         @questioncounter.save



	 
	 @choice = choiceid ? Choice.find(choiceid) : nil
	 if @choice and @choice.correct
		@correct = true
		session[:correct] += 1
	 else
		@correct = false
	 end
	 
	 session[:current] += 1
   end
  end

  def end
	 @correct = session[:correct]
	 @total   = session[:total]
	 
	 @score = @correct * 100 / @total 
         
         @user = current_user 
         @scoreboard = Scoreboard.new
         @scoreboard.user_id = @user.id
         @scoreboard.score_type = "archmaester"
         @scoreboard.score = @score

         @used_id_array = []
         @sessioncounters = SessionCounter.all
         @sessioncounters.each do |sc|
                @used_id_array << sc.used_session_id
         end

         unless @used_id_array.include?(request.session_options[:id])
                @sessioncounter = SessionCounter.new
                @sessioncounter.used_session_id = request.session_options[:id]
                @sessioncounter.save
                @scoreboard.save
         end

         @scoreboards = Scoreboard.where("score_type = 'archmaester'")
         @high_score_sorted_array_of_hashes = @scoreboards.sort_by { |hsh| hsh[:score] }.reverse
         @count = 1 
         @is_first_score = "true" 
         @previous_score = 9999999999
  end

  def create
  end

  def destroy
  end

end

app/helpers/challenge_archmaester_helper.rb
module ChallengeArchmaesterHelper
end

app/views/challenge_archmaester/answer.html.erb
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<div id="feedback-choices">
  <% @choices.each do |choice| %>
	 <% if choice.correct %>
		<p class="correct feedback-choice">
	 <% elsif choice == @choice %>
		<p class="incorrect feedback-choice">
	 <% else %>
		<p class="feedback-choice">
	 <% end %>
		<%= choice.text %>
	 </p>
  <% end %>
</div>

<p class="feedback">
  <% if @correct %>
	 Correct!
  <% else %>
	 Incorrect.
  <% end %>
</p>

<%= form_tag({:controller => "challenge_archmaester", :action => "question"}) do %>
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

app/views/challenge_archmaester/end.html.erb
<h1>Archmaester's Challenge Results</h1>
<p id="question">You answered correctly <%= @correct %> out of <%= @total %> questions.</p>

<p> Congratulations <%= @user.first_name %> you answered <%= @score %>% of the questions correctly! </p>

<table border="1">
  <tr>
    <th>Place</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Score</th>
    <th>House</th>
    <th>Profile</th>
  </tr>

<h1>Archmaester's Challenge High Scores</h1>
<% @high_score_sorted_array_of_hashes.each do |scb| %>
 <tr>
	<% if @is_first_score == "true" %>
        	<% @is_first_score = "false" %>
                <% @previous_score = scb.score %>
        <% else %>
		<% if @previous_score == scb.score %>
		<% else %>
			<% @count = @count + 1 %>
                        <% @previous_score = scb.score %>
		<% end %>
        <% end %>

   <td><%= @count.ordinalize %></td>
   <td><%= scb.user.first_name %></td>
   <td><%= scb.user.last_name %></td>
   <td><%= scb.score %></td>
   <td><%= scb.user.house_allegiance %>
   <td><%= link_to "details", user_path(:id => scb.user_id) %>
  </tr>
<% end %>
</table>

<%= form_tag({:controller => "challenge_archmaester", :action => "index"}, :method => "get") do %>
  <div class="center">
	 <%= submit_tag("Take another archmaester's challenge?", :class => "submit") %>
  </div>
<% end %>
<p> <%= link_to "Home", home_index_path %> </p>

app/views/challenge_archmaester/index.html.erb
<h1>Welcome to the Archmaester's Challenge!</h1>

<div class="center"> The Archmaester's Challenge will give the user the chance to test their A Song of Ice and Fire trivia skills with a group of hard difficulty questions. For the purpose of keeping this demonstration short, The Archmaester's Challenge will be restricted to 10 questions. When deployed into production the Archmaester's challenge will be 100 questions in length. Those 100 questions should be pulled randomly from a pool of 1000 questions or more, so as to give the user some replay value.
<br /><br />
Additionally, a timer may need to be added. If this was actually on the internet, anonymous users would just look the answers up before they answered them...

<br /><br />
</div>
<div class="center">
       <%= link_to "Take The Archmaester's Chalenge", challenge_archmaester_start_path %>
</div>

<%= form_tag({:controller => "challenge_archmaester", :action => "start"}, :method => "get") do %>
  <div class="center">
         <%= submit_tag("Begin!!!!", :class => "submit") %>
  </div>
<% end %>

app/views/challenge_archmaester/question.html.erb
<h1>Question <%= @current + 1 %> of <%= @total %></h1>
<p id="question"><%= @question.text %></p>

<%= form_tag({:controller => "challenge_archmaester", :action => "answer"}) do %>
  <% @choices.each do |choice| %>
	 <p class="choice">
		<%= radio_button_tag(:choice, choice.id) %>
		<%= label_tag("choice_".concat(choice.id.to_s).to_sym, choice.text) %>
	 </p>
  <% end %>
  
  <div class="center">
	 <%= submit_tag("Continue", :class => "submit") %>
  </div>
<% end %>

app/views/challenge_archmaester/start.html.erb
<h1>challenge_archmaester#start</h1>
<p>Find me in app/views/challenge_archmaester/start.html.erb</p>