config/routes.rb
Quiz::Application.routes.draw do
  get "home/index"
  devise_for :users
  get "quiz/index"
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"
  get "challenge_maester/index"
  post "challenge_maester/start"
  get "challenge_maester/start"
  get "challenge_maester/question"
  post "challenge_maester/question"
  post "challenge_maester/answer"
  get "challenge_maester/end"

  get "challenge_archmaester/index"
  post "challenge_archmaester/start"
  get "challenge_archmaester/start"
  get "challenge_archmaester/question"
  post "challenge_archmaester/question"
  post "challenge_archmaester/answer"
  get "challenge_archmaester/end"

  post "choices/create"
  post "choices/destroy"
  resources :questions
  root :to => "home#index"
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quiz" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" <%= link_to "Home", home_index_path  %></a>
          <div class="container-fluid nav-collapse">
	      <ul class="nav">
              <li><%= link_to "Quiz", quiz_index_path  %></li>
              <li><%= link_to "Maester's Challenge", challenge_maester_index_path  %></li>
              <li><%= link_to "Archmaester's Challenge", challenge_archmaester_index_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

	<div id="user_nav">
	  <% if user_signed_in? %>
	    &nbsp &nbsp Signed in as <%= current_user.email %>. Not you?
	    &nbsp &nbsp <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	  <% else %>
	    &nbsp &nbsp <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
	  <% end %>

    <div class="container-fluid">
      <div class="row-fluid">
<!--       <div class="span3">                          -->
<!--          <div class="well sidebar-nav">		-->								
<!--            <ul class="nav nav-list">		-->
<!--              <li class="nav-header">Sidebar</li>   -->
<!--              <li><%= link_to "Link1", "/path1"  %></li> -->
<!--              <li><%= link_to "Link2", "/path2"  %></li> -->
<!--              <li><%= link_to "Link3", "/path3"  %></li> -->
<!--            </ul> -->
<!--          </div><!--/.well -->
<!--       </div><!--/span--> 
        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>


</html>